texty -= scrollSpeed;
draw_set_font(lol);
draw_text_ext(textx, texty,"A GAME WHERE YOU PLAY AS A BUCKET (BETA v0.9)", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight,"A Game By IngoGamez", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *2, "IngoGamez:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *3, "E-DubzNG - Founder, Project Director, Programmer, Artist, Musician", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *4, "KAD - Founder, Project Director, Programmer, Artist, Musician", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *5, "dogdillon - Gameplay Co-Director", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *6, "Papyrus78677 - Assistant Programmer", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *7, "AGWYPaaB:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 8,"DIRECTORS:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 9,"E-DubzNG - Main Director", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 10,"KAD - Co-Director", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 11,"dogdillon - Co-Director of D-Money levels", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 12,"PROGRAMMING TEAM:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 13,"E-DubzNG - Lead Programmer", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 14,"ART TEAM:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 15,"E-DubzNG - Art Director, Animator", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 16, "KAD - Concept Artist", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 17,"SOUND TEAM:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 18,"E-DubzNG -  Music Director & Composer", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 19,"KAD - Music Director & Composer", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 20,"VOICE ACTORS:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 21,"dogdillon - Dummy", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 22,"Whoeverhitme - Pyro", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 23,"E-DubzNG - D-Money", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 24,"PLAY TESTERS:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 25,"DB", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 26,"NoahJam", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *27, "SPECIAL THANKS:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *28, "Tom Fulp - Creator of Newgrounds.com and E-Dubz's Main Inspiration", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *29, "YoYo Games - Creators of GameMaker", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight *30, "Seal - Found a bug i forgor to fix lol", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 31,"REND LOGO (Seen in D-Money's Day Out) belongs to RustyChroma", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 32,"MADE IN GAMEMAKER", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 33,"INSPIRED BY NEWGROUNDS.COM", lineHeight, room_width);