texty -= scrollSpeed;
draw_set_font(credFont);
draw_text_ext(textx, texty,"A GAME WHERE YOU PLAY AS A BUCKET (BETA v0.8)", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight,"A Game By IngoGamez", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 2,"Directors:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 3,"E-DubzNG - Main Director", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 4,"KAD - Co-Director", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 5,"dogdillon - Director of D-Money levels", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 6,"PROGRAMMING TEAM:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 7,"E-DubzNG - Lead Programmer", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 8,"ART TEAM:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 9,"E-DubzNG - Art Director, Animator", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 10, "KAD - Concept Artist", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 11,"SOUND TEAM:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 12,"E-DubzNG -  Music Director & Composer", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 13,"KAD - Music Director & Composer", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 14,"DB - Composer", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 15,"VOICE ACTORS:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 16,"dogdillon - Dummy", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 17,"Whoeverhitme - Pyro", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 18,"E-DubzNG - D-Money", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 19,"PLAY TESTERS:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 20,"DB", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 21,"NoahJam", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 22,"MADE IN GAMEMAKER", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 23,"INSPIRED BY NEWGROUNDS.COM", lineHeight, room_width);