texty -= scrollSpeed;
draw_set_font(credFont);
draw_text_ext(textx, texty,"A GAME WHERE YOU PLAY AS A BUCKET (BETA v0.7)", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight,"A Game By IngoGamez", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 2,"Directors:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 3,"E-DubzNG", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 4,"dogdillon", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 5,"KAD", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 6,"PROGRAMMING TEAM:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 7,"E-DubzNG", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 8,"ART TEAM:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 9,"E-DubzNG", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 10, "KAD", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 11,"SOUND TEAM:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 12,"E-DubzNG", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 13,"KAD", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 14,"DB", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 15,"VOICE ACTORS:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 16,"dogdillon - Dummy", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 17,"Whoeverhitme - Pyro", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 18,"PLAY TESTERS:", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 19,"DB", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 20,"NoahJam", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 21,"MADE IN GAMEMAKER", lineHeight, room_width);
draw_text_ext(textx, texty + lineHeight * 22,"INSPIRED BY NEWGROUNDS.COM", lineHeight, room_width);